In [3]:
import numpy as np
import pandas as pd

In [4]:
df_org=pd.read_csv("c:/Users/김다은/Downloads/accidentInfoListcsv.csv", sep=',')

In [5]:
df_org

,시군구,사망자수,중상자수,경상자수,사고유형,도로형태,가해운전자 차종,피해운전자 차종
0,서울특별시 강서구 방화동,0,0,1,차대사람 - 횡단중,교차로 - 교차로횡단보도내,승용,보행자
1,서울특별시 구로구 고척동,0,0,1,차대차 - 추돌,단일로 - 기타,이륜,승용
2,서울특별시 서초구 서초동,0,0,1,차대차 - 기타,기타 - 기타,승용,화물
3,서울특별시 중구 회현동2가,0,0,1,차대차 - 측면충돌,단일로 - 터널,승용,승용
4,서울특별시 성동구 행당동,0,0,1,차대사람 - 횡단중,교차로 - 교차로부근,승용,보행자
...,...,...,...,...,...,...,...,...
101272,서울특별시 중랑구 중화동,0,0,1,차량단독 - 공작물충돌,단일로 - 교량,승용,NaN
101273,서울특별시 송파구 장지동,0,0,1,차대차 - 측면충돌,교차로 - 교차로안,승용,승합
101274,서울특별시 서초구 반포동,0,1,1,차대차 - 기타,단일로 - 기타,승용,승용
101275,서울특별시 성동구 행당동,0,0,2,차대차 - 측면충돌,단일로 - 기타,승용,승용
101276,서울특별시 서초구 반포동,0,0,1,차대사람 - 기타,단일로 - 기타,승합,보행자

In [6]:
df_org.drop('사고유형',axis=1,inplace=True)
df_org

                   시군구  사망자수  중상자수  경상자수            도로형태 가해운전자 차종 피해운전자 차종
0        서울특별시 강서구 방화동     0     0     1  교차로 - 교차로횡단보도내       승용      보행자
1        서울특별시 구로구 고척동     0     0     1        단일로 - 기타       이륜       승용
2        서울특별시 서초구 서초동     0     0     1         기타 - 기타       승용       화물
3       서울특별시 중구 회현동2가     0     0     1        단일로 - 터널       승용       승용
4        서울특별시 성동구 행당동     0     0     1     교차로 - 교차로부근       승용      보행자
...                ...   ...   ...   ...             ...      ...      ...
101272   서울특별시 중랑구 중화동     0     0     1        단일로 - 교량       승용      NaN
101273   서울특별시 송파구 장지동     0     0     1      교차로 - 교차로안       승용       승합
101274   서울특별시 서초구 반포동     0     1     1        단일로 - 기타       승용       승용
101275   서울특별시 성동구 행당동     0     0     2        단일로 - 기타       승용       승용
101276   서울특별시 서초구 반포동     0     0     1        단일로 - 기타       승합      보행자

[101277 rows x 7 columns]

In [7]:
df_org['시군구']=df_org['시군구'].str.strip(to_strip='서울특별시')
df_org

              시군구  사망자수  중상자수  경상자수            도로형태 가해운전자 차종 피해운전자 차종
0         강서구 방화동     0     0     1  교차로 - 교차로횡단보도내       승용      보행자
1         구로구 고척동     0     0     1        단일로 - 기타       이륜       승용
2         서초구 서초동     0     0     1         기타 - 기타       승용       화물
3        중구 회현동2가     0     0     1        단일로 - 터널       승용       승용
4         성동구 행당동     0     0     1     교차로 - 교차로부근       승용      보행자
...           ...   ...   ...   ...             ...      ...      ...
101272    중랑구 중화동     0     0     1        단일로 - 교량       승용      NaN
101273    송파구 장지동     0     0     1      교차로 - 교차로안       승용       승합
101274    서초구 반포동     0     1     1        단일로 - 기타       승용       승용
101275    성동구 행당동     0     0     2        단일로 - 기타       승용       승용
101276    서초구 반포동     0     0     1        단일로 - 기타       승합      보행자

[101277 rows x 7 columns]

In [8]:
c1=df_org['시군구'].str.split().tolist()
result1=[]
result2=[]
for i in range(len(c1)):
    goo=c1[i][0]
    dong=c1[i][1]
    result1.append(goo)
    result2.append(dong)
len(result1), len(result2)

(101277, 101277)

In [9]:
df_org['자치구']=result1
df_org['행정구']=result2

In [10]:
df_org

,시군구,사망자수,중상자수,경상자수,도로형태,가해운전자 차종,피해운전자 차종,자치구,행정구
0,강서구 방화동,0,0,1,교차로 - 교차로횡단보도내,승용,보행자,강서구,방화동
1,구로구 고척동,0,0,1,단일로 - 기타,이륜,승용,구로구,고척동
2,서초구 서초동,0,0,1,기타 - 기타,승용,화물,서초구,서초동
3,중구 회현동2가,0,0,1,단일로 - 터널,승용,승용,중구,회현동2가
4,성동구 행당동,0,0,1,교차로 - 교차로부근,승용,보행자,성동구,행당동
...,...,...,...,...,...,...,...,...,...
101272,중랑구 중화동,0,0,1,단일로 - 교량,승용,NaN,중랑구,중화동
101273,송파구 장지동,0,0,1,교차로 - 교차로안,승용,승합,송파구,장지동
101274,서초구 반포동,0,1,1,단일로 - 기타,승용,승용,서초구,반포동
101275,성동구 행당동,0,0,2,단일로 - 기타,승용,승용,성동구,행당동
101276,서초구 반포동,0,0,1,단일로 - 기타,승합,보행자,서초구,반포동

In [11]:
df_org.drop('시군구',axis=1,inplace=True)

In [12]:
df=df_org[['자치구','행정구','사망자수','중상자수','경상자수','도로형태','가해운전자 차종','피해운전자 차종']]

In [13]:
df=df.loc[df['가해운전자 차종' or '피해운전자 차종']=='이륜']

In [14]:
df

         자치구   행정구  사망자수  중상자수  경상자수        도로형태 가해운전자 차종 피해운전자 차종
1        구로구   고척동     0     0     1    단일로 - 기타       이륜       승용
31      서대문구  북아현동     0     0     1    단일로 - 기타       이륜      보행자
38       중랑구   상봉동     0     0     1  교차로 - 교차로안       이륜       승합
40       구로구   천왕동     0     0     1  교차로 - 교차로안       이륜       이륜
49       마포구   도화동     0     0     1    단일로 - 기타       이륜      보행자
...      ...   ...   ...   ...   ...         ...      ...      ...
101221   서초구   방배동     0     0     1    단일로 - 기타       이륜       승용
101253   은평구   역촌동     0     1     0    단일로 - 기타       이륜      보행자
101255   동작구   사당동     0     0     2  교차로 - 교차로안       이륜       이륜
101257   양천구   신정동     0     1     0  교차로 - 교차로안       이륜       승용
101261   은평구   응암동     0     0     1    단일로 - 교량       이륜       이륜

[10341 rows x 8 columns]

In [15]:
road_split=df.도로형태.str.split(' - ')

road_split.index=range(0,10341)

print(road_split)

print(type(road_split))
print(type(road_split[0]))

#단일로, 교차로만 데이터로 넣기
road=road_split.str.get(0)

#필요없는 열 삭제
df.drop(['가해운전자 차종','피해운전자 차종'], axis=1,inplace=True)

df

df.drop(['도로형태'],axis=1,inplace=True)

df.index=range(10341)

df['도로형태']=road

0          [단일로, 기타]
1          [단일로, 기타]
2        [교차로, 교차로안]
3        [교차로, 교차로안]
4          [단일로, 기타]
            ...
10336      [단일로, 기타]
10337      [단일로, 기타]
10338    [교차로, 교차로안]
10339    [교차로, 교차로안]
10340      [단일로, 교량]
Name: 도로형태, Length: 10341, dtype: object
<class 'pandas.core.series.Series'>
<class 'list'>

In [66]:
df

        자치구   행정동  사망자수  중상자수  경상자수  단일로  교차로
0       구로구   고척동     0     0     1    1    0
1      서대문구  북아현동     0     0     1    1    0
2       중랑구   상봉동     0     0     1    0    1
3       구로구   천왕동     0     0     1    0    1
4       마포구   도화동     0     0     1    1    0
...     ...   ...   ...   ...   ...  ...  ...
10336   서초구   방배동     0     0     1    1    0
10337   은평구   역촌동     0     1     0    1    0
10338   동작구   사당동     0     0     2    0    1
10339   양천구   신정동     0     1     0    0    1
10340   은평구   응암동     0     0     1    1    0

[10341 rows x 7 columns]

In [49]:
len(df['행정동'].unique())

406

In [18]:
sglroad= df['도로형태']=='단일로'
crssroad= df['도로형태']=='교차로'
df['단일로']=sglroad
df['교차로']=crssroad
df['단일로']=df['단일로'].map(lambda x: 1 if x else 0)
df['교차로']=df['교차로'].map(lambda x: 1 if x else 0)

In [25]:
#컬럼명 변환
df=df.rename(columns={'행정구':'행정동'})

In [20]:
df.drop('도로형태',axis=1,inplace=True)

In [57]:
#행정동을 기준으로 총합 계산
grouped=df.groupby('행정동').sum()

C:\Users\김다은\AppData\Local\Temp\ipykernel_12148\2644079863.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped=df.groupby('행정동').sum()

In [58]:
grouped

      사망자수  중상자수  경상자수  단일로  교차로
행정동
가락동      0    26    79   22   65
가리봉동     3     4    29   11   16
가산동      3    14    45   25   20
가양동      0     4    30   10   18
가회동      0     0     1    0    1
...    ...   ...   ...  ...  ...
후암동      0     1     8    3    4
훈정동      0     0     1    1    0
휘경동      1    14    54   24   29
흑석동      0     4    25   17    7
흥인동      0     1     0    0    1

[406 rows x 5 columns]

In [64]:
df_loc=df[['자치구','행정동']]

In [65]:
df_loc

        자치구   행정동
0       구로구   고척동
1      서대문구  북아현동
2       중랑구   상봉동
3       구로구   천왕동
4       마포구   도화동
...     ...   ...
10336   서초구   방배동
10337   은평구   역촌동
10338   동작구   사당동
10339   양천구   신정동
10340   은평구   응암동

[10341 rows x 2 columns]