In [2]:
import numpy as np
import pandas as pd

In [18]:
import os
os.getcwd()

'C:\\Users\\김다은\\data_ana'

In [19]:
df_org=pd.read_csv("./accidentinfo.csv", sep=',')

In [20]:
df_org

,시군구,사고내용,사망자수,중상자수,경상자수,부상신고자수,사고유형,도로형태,가해운전자 차종,피해운전자 차종
0,서울특별시 은평구 응암동,중상사고,0,1,0,0,차대차 - 측면충돌,교차로 - 교차로안,승용,원동기
1,서울특별시 영등포구 영등포동,중상사고,0,1,3,0,차대차 - 기타,단일로 - 기타,이륜,승합
2,서울특별시 노원구 월계동,경상사고,0,0,1,0,차대차 - 추돌,단일로 - 기타,승용,승용
3,서울특별시 종로구 종로4가,경상사고,0,0,1,0,차대차 - 측면충돌,교차로 - 교차로안,승용,승용
4,서울특별시 강북구 미아동,경상사고,0,0,1,0,차대차 - 기타,단일로 - 기타,승용,이륜
...,...,...,...,...,...,...,...,...,...,...
31960,서울특별시 중랑구 중화동,경상사고,0,0,1,0,차량단독 - 공작물충돌,단일로 - 교량,승용,NaN
31961,서울특별시 송파구 장지동,경상사고,0,0,1,0,차대차 - 측면충돌,교차로 - 교차로안,승용,승합
31962,서울특별시 서초구 반포동,중상사고,0,1,1,0,차대차 - 기타,단일로 - 기타,승용,승용
31963,서울특별시 성동구 행당동,경상사고,0,0,2,0,차대차 - 측면충돌,단일로 - 기타,승용,승용
31964,서울특별시 서초구 반포동,경상사고,0,0,1,0,차대사람 - 기타,단일로 - 기타,승합,보행자

In [23]:
df_org.drop('사고내용',axis=1,inplace=True)
df_org

                   시군구  사망자수  중상자수  경상자수  부상신고자수        도로형태 가해운전자 차종 피해운전자 차종
0        서울특별시 은평구 응암동     0     1     0       0  교차로 - 교차로안       승용      원동기
1      서울특별시 영등포구 영등포동     0     1     3       0    단일로 - 기타       이륜       승합
2        서울특별시 노원구 월계동     0     0     1       0    단일로 - 기타       승용       승용
3       서울특별시 종로구 종로4가     0     0     1       0  교차로 - 교차로안       승용       승용
4        서울특별시 강북구 미아동     0     0     1       0    단일로 - 기타       승용       이륜
...                ...   ...   ...   ...     ...         ...      ...      ...
31960    서울특별시 중랑구 중화동     0     0     1       0    단일로 - 교량       승용      NaN
31961    서울특별시 송파구 장지동     0     0     1       0  교차로 - 교차로안       승용       승합
31962    서울특별시 서초구 반포동     0     1     1       0    단일로 - 기타       승용       승용
31963    서울특별시 성동구 행당동     0     0     2       0    단일로 - 기타       승용       승용
31964    서울특별시 서초구 반포동     0     0     1       0    단일로 - 기타       승합      보행자

[31965 rows x 8 columns]

In [24]:
df_org['시군구']=df_org['시군구'].str.strip(to_strip='서울특별시')
df_org

              시군구  사망자수  중상자수  경상자수  부상신고자수        도로형태 가해운전자 차종 피해운전자 차종
0         은평구 응암동     0     1     0       0  교차로 - 교차로안       승용      원동기
1       영등포구 영등포동     0     1     3       0    단일로 - 기타       이륜       승합
2         노원구 월계동     0     0     1       0    단일로 - 기타       승용       승용
3        종로구 종로4가     0     0     1       0  교차로 - 교차로안       승용       승용
4         강북구 미아동     0     0     1       0    단일로 - 기타       승용       이륜
...           ...   ...   ...   ...     ...         ...      ...      ...
31960     중랑구 중화동     0     0     1       0    단일로 - 교량       승용      NaN
31961     송파구 장지동     0     0     1       0  교차로 - 교차로안       승용       승합
31962     서초구 반포동     0     1     1       0    단일로 - 기타       승용       승용
31963     성동구 행당동     0     0     2       0    단일로 - 기타       승용       승용
31964     서초구 반포동     0     0     1       0    단일로 - 기타       승합      보행자

[31965 rows x 8 columns]

In [25]:
c1=df_org['시군구'].str.split().tolist()
result1=[]
result2=[]
for i in range(len(c1)):
    goo=c1[i][0]
    dong=c1[i][1]
    result1.append(goo)
    result2.append(dong)
len(result1), len(result2)

(31965, 31965)

In [26]:
df_org['자치구']=result1
df_org['행정구']=result2

In [27]:
df_org

,시군구,사망자수,중상자수,경상자수,부상신고자수,도로형태,가해운전자 차종,피해운전자 차종,자치구,행정구
0,은평구 응암동,0,1,0,0,교차로 - 교차로안,승용,원동기,은평구,응암동
1,영등포구 영등포동,0,1,3,0,단일로 - 기타,이륜,승합,영등포구,영등포동
2,노원구 월계동,0,0,1,0,단일로 - 기타,승용,승용,노원구,월계동
3,종로구 종로4가,0,0,1,0,교차로 - 교차로안,승용,승용,종로구,종로4가
4,강북구 미아동,0,0,1,0,단일로 - 기타,승용,이륜,강북구,미아동
...,...,...,...,...,...,...,...,...,...,...
31960,중랑구 중화동,0,0,1,0,단일로 - 교량,승용,NaN,중랑구,중화동
31961,송파구 장지동,0,0,1,0,교차로 - 교차로안,승용,승합,송파구,장지동
31962,서초구 반포동,0,1,1,0,단일로 - 기타,승용,승용,서초구,반포동
31963,성동구 행당동,0,0,2,0,단일로 - 기타,승용,승용,성동구,행당동
31964,서초구 반포동,0,0,1,0,단일로 - 기타,승합,보행자,서초구,반포동

In [28]:
df_org.drop('시군구',axis=1,inplace=True)

In [29]:
df=df_org[['자치구','행정구','사망자수','중상자수','경상자수','도로형태','가해운전자 차종','피해운전자 차종']]

In [30]:
df=df.loc[df['가해운전자 차종' or '피해운전자 차종']=='이륜']

In [31]:
df

        자치구    행정구  사망자수  중상자수  경상자수            도로형태 가해운전자 차종 피해운전자 차종
1      영등포구   영등포동     0     1     3        단일로 - 기타       이륜       승합
10      마포구    공덕동     0     1     0      교차로 - 교차로안       이륜       승합
13      용산구  한강로2가     0     1     4     교차로 - 교차로부근       이륜       승합
22      강동구    성내동     0     0     1      교차로 - 교차로안       이륜       승용
29      강동구    성내동     0     0     1  교차로 - 교차로횡단보도내       이륜      보행자
...     ...    ...   ...   ...   ...             ...      ...      ...
31909   서초구    방배동     0     0     1        단일로 - 기타       이륜       승용
31941   은평구    역촌동     0     1     0        단일로 - 기타       이륜      보행자
31943   동작구    사당동     0     0     2      교차로 - 교차로안       이륜       이륜
31945   양천구    신정동     0     1     0      교차로 - 교차로안       이륜       승용
31949   은평구    응암동     0     0     1        단일로 - 교량       이륜       이륜

[3545 rows x 8 columns]

In [32]:
road_split=df.도로형태.str.split(' - ')

road_split.index=range(0,3545)

print(road_split)

print(type(road_split))
print(type(road_split[0]))

#단일로, 교차로만 데이터로 넣기
road=road_split.str.get(0)

#필요없는 열 삭제
df.drop(['가해운전자 차종','피해운전자 차종'], axis=1,inplace=True)

df

df.drop(['도로형태'],axis=1,inplace=True)

df.index=range(3545)

df['도로형태']=road

0             [단일로, 기타]
1           [교차로, 교차로안]
2          [교차로, 교차로부근]
3           [교차로, 교차로안]
4       [교차로, 교차로횡단보도내]
             ...
3540          [단일로, 기타]
3541          [단일로, 기타]
3542        [교차로, 교차로안]
3543        [교차로, 교차로안]
3544          [단일로, 교량]
Name: 도로형태, Length: 3545, dtype: object
<class 'pandas.core.series.Series'>
<class 'list'>

In [33]:
df

       자치구    행정구  사망자수  중상자수  경상자수 도로형태
0     영등포구   영등포동     0     1     3  단일로
1      마포구    공덕동     0     1     0  교차로
2      용산구  한강로2가     0     1     4  교차로
3      강동구    성내동     0     0     1  교차로
4      강동구    성내동     0     0     1  교차로
...    ...    ...   ...   ...   ...  ...
3540   서초구    방배동     0     0     1  단일로
3541   은평구    역촌동     0     1     0  단일로
3542   동작구    사당동     0     0     2  교차로
3543   양천구    신정동     0     1     0  교차로
3544   은평구    응암동     0     0     1  단일로

[3545 rows x 6 columns]

In [34]:
sglroad= df['도로형태']=='단일로'
crssroad= df['도로형태']=='교차로'
df['단일로']=sglroad
df['교차로']=crssroad
df['단일로']=df['단일로'].map(lambda x: 1 if x else 0)
df['교차로']=df['교차로'].map(lambda x: 1 if x else 0)

In [39]:
df

       자치구    행정동  사망자수  중상자수  경상자수 도로형태  단일로  교차로
0     영등포구   영등포동     0     1     3  단일로    1    0
1      마포구    공덕동     0     1     0  교차로    0    1
2      용산구  한강로2가     0     1     4  교차로    0    1
3      강동구    성내동     0     0     1  교차로    0    1
4      강동구    성내동     0     0     1  교차로    0    1
...    ...    ...   ...   ...   ...  ...  ...  ...
3540   서초구    방배동     0     0     1  단일로    1    0
3541   은평구    역촌동     0     1     0  단일로    1    0
3542   동작구    사당동     0     0     2  교차로    0    1
3543   양천구    신정동     0     1     0  교차로    0    1
3544   은평구    응암동     0     0     1  단일로    1    0

[3545 rows x 8 columns]

In [38]:
#컬럼명 변환
df=df.rename(columns={'행정구':'행정동'})

In [40]:
df.drop('도로형태',axis=1,inplace=True)

In [41]:
#행정동을 기준으로 총합 계산
grouped=df.groupby(['행정동','자치구']).sum()

In [42]:
grouped

           사망자수  중상자수  경상자수  단일로  교차로
행정동  자치구
가락동  송파구      0     8    32   14   17
가리봉동 구로구      1     2    10    4    6
가산동  금천구      2     5    17    9    8
가양동  강서구      0     1     7    3    4
가회동  종로구      0     0     1    0    1
...         ...   ...   ...  ...  ...
효창동  용산구      0     0     3    1    2
후암동  용산구      0     1     3    2    0
훈정동  종로구      0     0     1    1    0
휘경동  동대문구     1     6    16    7   14
흑석동  동작구      0     1     4    5    0

[334 rows x 5 columns]

In [43]:
#행정동과 법정동을 매칭시켜주는 파일을 불러옴
df_match= pd.read_csv('./행정동 법정동 코드.csv', encoding='utf-8')

In [44]:
df_match

            행정동코드      시도명  시군구명   읍면동명       법정동코드    동리명      생성일자
0      1100000000    서울특별시   NaN    NaN  1100000000  서울특별시  19880423
1      1111000000    서울특별시   종로구    NaN  1111000000    종로구  19880423
2      1111051500    서울특별시   종로구  청운효자동  1111010100    청운동  20081101
3      1111051500    서울특별시   종로구  청운효자동  1111010200    신교동  20081101
4      1111051500    서울특별시   종로구  청운효자동  1111010300    궁정동  20081101
...           ...      ...   ...    ...         ...    ...       ...
21734  5013061000  제주특별자치도  서귀포시    중문동  5013011400    대포동  20060701
21735  5013061000  제주특별자치도  서귀포시    중문동  5013011800    하원동  20060701
21736  5013062000  제주특별자치도  서귀포시    예래동  5013011900    색달동  20060701
21737  5013062000  제주특별자치도  서귀포시    예래동  5013012000    상예동  20060701
21738  5013062000  제주특별자치도  서귀포시    예래동  5013012100    하예동  20060701

[21739 rows x 7 columns]

In [45]:
#서울시, 종로구 등 시군구 단위까지만 있는 것은 값이 없기 때문에 결측치로 처리됨 : 해당 결측치 제거
df_match=df_match.dropna()

In [46]:
df_match

            행정동코드      시도명  시군구명   읍면동명       법정동코드  동리명      생성일자
2      1111051500    서울특별시   종로구  청운효자동  1111010100  청운동  20081101
3      1111051500    서울특별시   종로구  청운효자동  1111010200  신교동  20081101
4      1111051500    서울특별시   종로구  청운효자동  1111010300  궁정동  20081101
5      1111051500    서울특별시   종로구  청운효자동  1111010400  효자동  20081101
6      1111051500    서울특별시   종로구  청운효자동  1111010500  창성동  20081101
...           ...      ...   ...    ...         ...  ...       ...
21734  5013061000  제주특별자치도  서귀포시    중문동  5013011400  대포동  20060701
21735  5013061000  제주특별자치도  서귀포시    중문동  5013011800  하원동  20060701
21736  5013062000  제주특별자치도  서귀포시    예래동  5013011900  색달동  20060701
21737  5013062000  제주특별자치도  서귀포시    예래동  5013012000  상예동  20060701
21738  5013062000  제주특별자치도  서귀포시    예래동  5013012100  하예동  20060701

[21297 rows x 7 columns]

In [47]:
#행정동/법정동 코드를 10자리->8자리로 변경
df_match['행정동코드']=(df_match['행정동코드']/100).astype(np.int64)
df_match['법정동코드']=(df_match['법정동코드']/100).astype(np.int64)

C:\Users\김다은\AppData\Local\Temp\ipykernel_16420\3424024333.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_match['행정동코드']=(df_match['행정동코드']/100).astype(np.int64)
C:\Users\김다은\AppData\Local\Temp\ipykernel_16420\3424024333.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_match['법정동코드']=(df_match['법정동코드']/100).astype(np.int64)

In [57]:
#하나의 행정동이 몇개의 법정동으로 이루어져 있는지 확인
bup_count=df_match[['행정동코드','법정동코드']].groupby('행정동코드').count().rename(columns={'법정동코드':'법정동갯수'}).reset_index()
bup_count

         행정동코드  법정동갯수
0     11110515     10
1     11110530     12
2     11110540      7
3     11110550      3
4     11110560      2
...        ...    ...
3534  50130580      1
3535  50130590      3
3536  50130600      4
3537  50130610      4
3538  50130620      3

[3539 rows x 2 columns]

In [67]:
#df_match에 추가
df_match=pd.merge(df_match,bup_count,how='left').loc[df_match['시도명']=='서울특별시',:]
df_match

        행정동코드    시도명 시군구명   읍면동명     법정동코드  동리명      생성일자  법정동갯수
0    11110515  서울특별시  종로구  청운효자동  11110101  청운동  20081101     10
1    11110515  서울특별시  종로구  청운효자동  11110102  신교동  20081101     10
2    11110515  서울특별시  종로구  청운효자동  11110103  궁정동  20081101     10
3    11110515  서울특별시  종로구  청운효자동  11110104  효자동  20081101     10
4    11110515  서울특별시  종로구  청운효자동  11110105  창성동  20081101     10
..        ...    ...  ...    ...       ...  ...       ...    ...
738  11740650  서울특별시  강동구  성내제2동  11740108  성내동  19880423      1
739  11740660  서울특별시  강동구  성내제3동  11740108  성내동  19880423      1
740  11740685  서울특별시  강동구     길동  11740105   길동  20080707      1
741  11740690  서울특별시  강동구  둔촌제1동  11740106  둔촌동  19880423      1
742  11740700  서울특별시  강동구  둔촌제2동  11740106  둔촌동  19880423      1

[743 rows x 8 columns]

In [62]:
#서울시 행정동별 인구데이터 불러오기
df_stat=pd.read_csv('C:/Users/김다은/Desktop/개인분석과제/서울시 행정동별 생활인구(내국인).csv', encoding='utf-8', index_col=None)

In [63]:
df_stat

        기준일ID  시간대구분     행정동코드      총생활인구수
0    20211231     23  11590520  15392.3606
1    20211231     23  11110700   6766.6507
2    20211231     23  11650550   1944.7150
3    20211231     23  11650580  17357.3845
4    20211231     23  11560710  20246.6744
..        ...    ...       ...         ...
419  20211231     23  11470540  21687.6749
420  20211231     23  11740685  56597.5455
421  20211231     23  11500611  33165.7067
422  20211231     23  11215810  36194.0265
423  20211231     23  11560550  22589.9182

[424 rows x 4 columns]

In [69]:
#행정동-법정동 매칭 정보와 통계치를 붙임
df2=pd.merge(df_match,df_stat,how='left')
df2.dropna()

,행정동코드,시도명,시군구명,읍면동명,법정동코드,동리명,생성일자,법정동갯수,기준일ID,시간대구분,총생활인구수
0,11110515,서울특별시,종로구,청운효자동,11110101,청운동,20081101,10,20211231.0,23.0,15568.7728
1,11110515,서울특별시,종로구,청운효자동,11110102,신교동,20081101,10,20211231.0,23.0,15568.7728
2,11110515,서울특별시,종로구,청운효자동,11110103,궁정동,20081101,10,20211231.0,23.0,15568.7728
3,11110515,서울특별시,종로구,청운효자동,11110104,효자동,20081101,10,20211231.0,23.0,15568.7728
4,11110515,서울특별시,종로구,청운효자동,11110105,창성동,20081101,10,20211231.0,23.0,15568.7728
...,...,...,...,...,...,...,...,...,...,...,...
738,11740650,서울특별시,강동구,성내제2동,11740108,성내동,19880423,1,20211231.0,23.0,26922.9780
739,11740660,서울특별시,강동구,성내제3동,11740108,성내동,19880423,1,20211231.0,23.0,28098.8671
740,11740685,서울특별시,강동구,길동,11740105,길동,20080707,1,20211231.0,23.0,56597.5455
741,11740690,서울특별시,강동구,둔촌제1동,11740106,둔촌동,19880423,1,20211231.0,23.0,5485.8371
742,11740700,서울특별시,강동구,둔촌제2동,11740106,둔촌동,19880423,1,20211231.0,23.0,28863.0769

In [72]:
#서울시 행정동 수는 426
df2.groupby('행정동코드').읍면동명.count()

행정동코드
11110515    10
11110530    12
11110540     7
11110550     3
11110560     2
            ..
11740650     1
11740660     1
11740685     1
11740690     1
11740700     1
Name: 읍면동명, Length: 426, dtype: int64

In [75]:
grouped=grouped.reset_index()

In [76]:
grouped

      행정동   자치구  사망자수  중상자수  경상자수  단일로  교차로
0     가락동   송파구     0     8    32   14   17
1    가리봉동   구로구     1     2    10    4    6
2     가산동   금천구     2     5    17    9    8
3     가양동   강서구     0     1     7    3    4
4     가회동   종로구     0     0     1    0    1
..    ...   ...   ...   ...   ...  ...  ...
329   효창동   용산구     0     0     3    1    2
330   후암동   용산구     0     1     3    2    0
331   훈정동   종로구     0     0     1    1    0
332   휘경동  동대문구     1     6    16    7   14
333   흑석동   동작구     0     1     4    5    0

[334 rows x 7 columns]

In [77]:
df2

,행정동코드,시도명,시군구명,읍면동명,법정동코드,동리명,생성일자,법정동갯수,기준일ID,시간대구분,총생활인구수
0,11110515,서울특별시,종로구,청운효자동,11110101,청운동,20081101,10,20211231.0,23.0,15568.7728
1,11110515,서울특별시,종로구,청운효자동,11110102,신교동,20081101,10,20211231.0,23.0,15568.7728
2,11110515,서울특별시,종로구,청운효자동,11110103,궁정동,20081101,10,20211231.0,23.0,15568.7728
3,11110515,서울특별시,종로구,청운효자동,11110104,효자동,20081101,10,20211231.0,23.0,15568.7728
4,11110515,서울특별시,종로구,청운효자동,11110105,창성동,20081101,10,20211231.0,23.0,15568.7728
...,...,...,...,...,...,...,...,...,...,...,...
738,11740650,서울특별시,강동구,성내제2동,11740108,성내동,19880423,1,20211231.0,23.0,26922.9780
739,11740660,서울특별시,강동구,성내제3동,11740108,성내동,19880423,1,20211231.0,23.0,28098.8671
740,11740685,서울특별시,강동구,길동,11740105,길동,20080707,1,20211231.0,23.0,56597.5455
741,11740690,서울특별시,강동구,둔촌제1동,11740106,둔촌동,19880423,1,20211231.0,23.0,5485.8371
742,11740700,서울특별시,강동구,둔촌제2동,11740106,둔촌동,19880423,1,20211231.0,23.0,28863.0769

In [78]:
#df2 변수 정리
df2=df2[['읍면동명','행정동코드','총생활인구수']]
df2

      읍면동명     행정동코드      총생활인구수
0    청운효자동  11110515  15568.7728
1    청운효자동  11110515  15568.7728
2    청운효자동  11110515  15568.7728
3    청운효자동  11110515  15568.7728
4    청운효자동  11110515  15568.7728
..     ...       ...         ...
738  성내제2동  11740650  26922.9780
739  성내제3동  11740660  28098.8671
740     길동  11740685  56597.5455
741  둔촌제1동  11740690   5485.8371
742  둔촌제2동  11740700  28863.0769

[743 rows x 3 columns]